
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { AppSettings, Entry, User } from './types';

export const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0
  }).format(amount);
};

// Safe formatting for PDF (No Symbols)
export const formatCurrencyPDF = (amount: number) => {
  return `Rs. ${amount.toLocaleString('en-IN')}/-`;
};

export const formatDate = (timestamp: number) => {
  return new Date(timestamp).toLocaleDateString('en-IN');
};

// Marathi Translations for Work Types
export const WORK_TYPE_LABELS: Record<string, string> = {
  'Rotaweter': 'रोटावेटर',
  'Nagarni': 'नांगरणी',
  'Sapatikaran': 'सपाटीकरण',
  'Transport_Maati': 'माती वाहतूक',
  'Transport_Khat': 'खत वाहतूक',
  'Other': 'इतर'
};

// Marathi Translations for Expense Types
export const EXPENSE_TYPE_LABELS: Record<string, string> = {
  'Diesel': 'डिझेल',
  'Repair': 'दुरुस्ती',
  'Salary': 'पगार',
  'Maintenance': 'देखभाल',
  'Other': 'इतर'
};

// Full Ledger PDF
export const generatePDF = (user: User, entries: Entry[], settings: AppSettings) => {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(128, 0, 0); // Maroon
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text(settings.ownerName, 105, 15, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text(`Mobile: ${settings.ownerMob} | Tractor: ${settings.tractorModel}`, 105, 25, { align: 'center' });
  doc.text(`Authorized Bill`, 105, 32, { align: 'center' });

  // Client Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text(`Client: ${user.name}`, 14, 55);
  doc.text(`Mobile: ${user.mob}`, 14, 62);
  doc.text(`Date: ${new Date().toLocaleDateString('en-IN')}`, 150, 55);

  // Table Data
  const tableData = entries.map(e => [
    new Date(e.timestamp).toLocaleDateString('en-IN'),
    e.type === 'WORK' ? (e.workType || '-') : 'Payment',
    e.details || '-',
    e.quantity ? `${e.quantity}` : '-',
    e.rate ? formatCurrencyPDF(e.rate) : '-',
    e.type === 'WORK' ? formatCurrencyPDF(e.amount) : '-',
    e.type === 'PAYMENT' ? formatCurrencyPDF(e.amount) : '-',
  ]);

  let totalWork = 0;
  let totalPaid = 0;
  entries.forEach(e => {
    if (e.type === 'WORK') totalWork += e.amount;
    else if (e.status === 'COMPLETED') totalPaid += e.amount;
  });

  // @ts-ignore
  autoTable(doc, {
    startY: 70,
    head: [['Date', 'Description', 'Loc/Details', 'Qty', 'Rate', 'Debit', 'Credit']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [128, 0, 0] },
    foot: [['', '', '', '', 'Total', formatCurrencyPDF(totalWork), formatCurrencyPDF(totalPaid)]],
    footStyles: { fillColor: [200, 200, 200], textColor: [0, 0, 0], fontStyle: 'bold' }
  });

  // Footer
  // @ts-ignore
  const finalY = doc.lastAutoTable.finalY + 20;
  
  const balance = totalWork - totalPaid;
  const balanceText = balance > 0 ? `Net Payable: ${formatCurrencyPDF(balance)}` : `Advance Balance: ${formatCurrencyPDF(Math.abs(balance))}`;

  doc.setFontSize(14);
  doc.setTextColor(128, 0, 0);
  doc.text(balanceText, 14, finalY);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text("Thank you for your business!", 105, finalY + 20, { align: 'center' });
  doc.text("Generated by OJA System V17", 105, finalY + 26, { align: 'center' });

  doc.save(`${user.name}_Bill.pdf`);
};

// Single Payment Receipt PDF (NOC Style)
export const generateReceiptPDF = (entry: Entry, user: User, settings: AppSettings) => {
    const doc = new jsPDF('landscape', 'mm', [210, 99]); // 1/3rd A4 size approx for Receipt
    
    // Border
    doc.setLineWidth(1);
    doc.setDrawColor(128, 0, 0);
    doc.rect(5, 5, 200, 89);
    
    // Header
    doc.setFillColor(128, 0, 0);
    doc.rect(5, 5, 200, 20, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(settings.ownerName.toUpperCase(), 105, 14, { align: 'center' });
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Tractor Services | Mob: ${settings.ownerMob}`, 105, 21, { align: 'center' });

    // Receipt Title (Pure English to avoid font issues)
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("PAYMENT RECEIPT", 105, 35, { align: 'center' });
    doc.setLineWidth(0.5);
    doc.line(70, 36, 140, 36);

    // Details Grid
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    
    const leftColX = 20;
    const rightColX = 120;
    const startY = 45;
    const gap = 8;

    // Fix Payment Mode Text (Remove "Pending Approval")
    let paymentMode = entry.details || 'Cash';
    if(paymentMode.includes('Pending')) {
        paymentMode = "Online Payment";
    }

    // Row 1
    doc.text(`Receipt No: #${entry.id.slice(-6)}`, leftColX, startY);
    doc.text(`Date: ${formatDate(entry.timestamp)}`, rightColX, startY);

    // Row 2
    doc.text(`Received From: ${user.name}`, leftColX, startY + gap);
    doc.text(`Village: ${user.village || '-'}`, rightColX, startY + gap);

    // Row 3
    doc.text(`Payment Mode: ${paymentMode}`, leftColX, startY + gap * 2);
    doc.text(`Status: CONFIRMED`, rightColX, startY + gap * 2);
    
    // Amount Box
    doc.setFillColor(240, 240, 240);
    doc.rect(20, startY + gap * 3, 170, 15, 'F');
    doc.setTextColor(128, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    // Use formatCurrencyPDF to avoid symbol issues
    doc.text(`AMOUNT RECEIVED: ${formatCurrencyPDF(entry.amount)}`, 105, startY + gap * 3 + 10, { align: 'center' });

    // Footer / Signature
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    
    doc.text("Authorized Signature", 170, 80, { align: 'center' });
    
    // ADDED: Owner Name below signature
    doc.setFont("helvetica", "bold");
    doc.text(`(${settings.ownerName})`, 170, 85, { align: 'center' });
    
    doc.setFont("helvetica", "normal");
    doc.text("Subject to Realisation", 20, 85);
    
    doc.save(`Receipt_${entry.id}.pdf`);
};

export const openWhatsApp = (mob: string, message: string) => {
  const url = `https://wa.me/91${mob}?text=${encodeURIComponent(message)}`;
  window.open(url, '_blank');
};

export const openSMS = (mob: string, message: string) => {
    // SMS protocol usually separate numbers with comma or semicolon depending on OS, but here just one number
    const url = `sms:${mob}?body=${encodeURIComponent(message)}`;
    window.open(url, '_self');
};
